markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: XuChengshan
author: "徐成山"
email: 2630517357@qq.com
name: "徐成山的个人博客"
url: https://xuchengshan.github.io/index
domain: https://xuchengshan.github.io/index
all_categories: [
["android", "Android开发","/posts/android.html"], 
["program", "软件编程","/posts/program.html"],
["web", "Web建站","/posts/web.html"], 
["linux", "Linux相关","/posts/linux.html"],
["read", "读书笔记","/posts/read.html"], 
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 1
paginate_path: "posts/page:num"
timezone: Asia/Shanghai

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
